MESSAGE(STATUS "Post Build Platform Dependancies Configuration")

# ───────── WINDOWS ──────────

IF(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
	IF(QQUICKMATERIALHELPERGALLERY_BUILD_EXE)
		INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/BuildQtWindowsCMake.cmake)

		MESSAGE(STATUS "Add QtWindowsCMake for ${QQUICKMATERIALHELPERGALLERY_TARGET}")
		add_qt_windows_exe( ${QQUICKMATERIALHELPERGALLERY_TARGET} 
			ALL
		    NAME "QQuickMaterialHelperGallery"
		    VERSION ${QQUICKMATERIALHELPERGALLERY_VERSION}
		    PUBLISHER "Ereimul"
		    PRODUCT_URL "www.qquickcontrols.com"
		    PACKAGE "org.qquickcontrols.qquickHelperGallery"
		    FILE_EXTENSION "qquickHelperGallery"
		    ICON ${CMAKE_CURRENT_SOURCE_DIR}/platform/windows/icon.ico
		    ICON_RC ${CMAKE_CURRENT_SOURCE_DIR}/platform/windows/icon.rc
		    QML_DIR ${QT_WINDOWS_QT_ROOT}/qml
		    NO_TRANSATION
		    VERBOSE_LEVEL_DEPLOY 1
		    VERBOSE_INSTALLER
		 )

	ENDIF(QQUICKMATERIALHELPERGALLERY_BUILD_EXE)
ENDIF(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")

# ────────── LINUX ───────────

# ────────── MACOS ───────────

# ───────── ANDROID ──────────

IF(${CMAKE_SYSTEM_NAME} STREQUAL "Android")

	INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/BuildQtAndroidCMake.cmake)
	
    IF(QQUICKMATERIALHELPERGALLERY_ANDROID_KEYSTORE)
    SET(KEYSTORE_SIGNATURE
    	KEYSTORE ${QQUICKMATERIALHELPERGALLERY_ANDROID_KEYSTORE} ${QQUICKMATERIALHELPERGALLERY_ANDROID_KEYSTORE_ALIAS}
   		KEYSTORE_PASSWORD ${QQUICKMATERIALHELPERGALLERY_ANDROID_KEYSTORE_PASSWORD}
    	)
    ENDIF(QQUICKMATERIALHELPERGALLERY_ANDROID_KEYSTORE)

    add_qt_android_apk(${QQUICKMATERIALHELPERGALLERY_TARGET}Apk ${QQUICKMATERIALHELPERGALLERY_TARGET}
    	NAME "QQuickMaterialHelperGallery"
    	VERSION_NAME ${QQUICKMATERIALHELPERGALLERY_VERSION}
    	VERSION_CODE 1
    	PACKAGE_NAME "org.qquickcontrols.qquickHelperGallery"
    	PACKAGE_SOURCES  ${CMAKE_CURRENT_SOURCE_DIR}/platform/android/src
    	ANDROID_MANIFEST_IN_PATH ${CMAKE_CURRENT_SOURCE_DIR}/platform/android/AndroidManifest.xml.in
    	${KEYSTORE_SIGNATURE}
    	)

ENDIF(${CMAKE_SYSTEM_NAME} STREQUAL "Android")

# ─────────── IOS ────────────